services:
  - type: web
    name: tiktok-downloader
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_ENV
        value: production
      - key: DEBUG
        value: false
      - key: YTDL_NO_UPDATE
        value: true